version: '3.0'
services:
  # Container
  ros2-nav:
    # Build or Reference the image
    build: .
    image: pomelo/ros2-humble:navigation
    container_name: TTennis-nav
    stdin_open: true
    tty: true
    privileged: true
    command: bash
    network_mode: host

    # Container Settings
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority 
      
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
